WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Personel.cs
namespace WebApplication1.Models
{
    public enum Gender
    {
        kadın=1,
        erkek=2,
        none=3
    }
    public class Personel
    {
        public Personel()
        {
            
        }
        public Personel(int ıd, string name, string address, string cv, Gender gender)
        {
            Id = ıd;
            Name = name;
            Address = address;
            Cv = cv;
            Gender = gender;
        }

        public int Id { get; set; }

        public string    Name { get; set; }
        public string Address { get; set; }
        public string Cv { get; set; }
        public Gender Gender { get; set; } 

    }
}

WebApplication1/Models/Product.cs
namespace WebApplication1.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

WebApplication1/Models/Userİnformation.cs
namespace WebApplication1.Models
{
    public class Userİnformation
    {
        public string UserName { get; set; }
        public string Password { get; set; }


    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LayoutTest(int id)
        {

            Console.WriteLine("değer yakalandı " + id);

            return View();
        }
        public IActionResult Privacy()
        {

            throw new Exception();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class PersonelController : Controller
    {


        List<Personel> list = new List<Personel>()
        {

            new(1,"hasan","ankara","beni işe al 1",Gender.erkek),
            new(2,"serger","adana","beni işe al 2 ",Gender.erkek),
            new(3,"burcu","ankara","beni işe al 3 " ,Gender.kadın),
            new(4,"ozan","ısparta","beni işe al 4",Gender.erkek),
            new(5,"mehmet","ankara","beni işe al 5",Gender.erkek),
            new(6,"x","ankara","beni işe al 5",Gender.none),


        };
        public IActionResult Index()
        {
            return View();
        }

        //   personel/list
        public IActionResult List()
        {

            return View(list);
        }

        public IActionResult Profile(int id)
        {
            var data = list.Where(x => x.Id == id).FirstOrDefault();


            return View(data);
        }
    }
}

WebApplication1/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection.Metadata.Ecma335;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {

        public static List<Product> list = new();

       

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(Product product)
        {
            list.Add(product);

            return RedirectToAction("List");
        }

        public IActionResult delete(int id)
        {
            var data= list.Where(x => x.Id == id).FirstOrDefault();
            list.Remove(data);
            return RedirectToAction("List");
        }
        public IActionResult List()
        {
            return View(list);
        }
    }
}

WebApplication1/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

      
        public IActionResult Login()
        {

            return View();
        }

        [HttpPost()]
        public IActionResult Login(Userİnformation userİnformation)
        {

            if (userİnformation.UserName == "hasan" && userİnformation.Password=="123")
            {
            return RedirectToAction("index");
            }
                return Redirect("/home/error");
        }

    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}



@*          www.hasan.com/home/index/id     *@

@*  wwww.merkez.com/personel/profil/1  berk *@
@*  wwww.merkez.com/personel/profil/2 *@
@*  wwww.merkez.com/personel/profil/3 *@

<a class="btn btn-outline-primary"  asp-route-id ="1" asp-action="LayoutTest" asp-controller="Home">Test sayfasına git</a>


@section Scripts{

    <script>

        console.log("asd");

    </script>

}


@section internalCss{


    <style>

    
    a{
        color:red;
    }
    </style>

}



<p>data asdajdlşajsdkajskldj</p>
<p>data asdajdlşajsdkajskldj</p>
<p>data asdajdlşajsdkajskldj</p>
<p>data asdajdlşajsdkajskldj</p>
<p>data asdajdlşajsdkajskldj</p>
<p>data asdajdlşajsdkajskldj</p>

WebApplication1/Views/Home/LayoutTest.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@{

    Layout = "_Layout2";
}


<h2>
    ben layout2 kullanıyorum
</h2>

WebApplication1/Views/Personel/List.cshtml
@{
    ViewData["Title"] = "List";
}



@model List<Personel>



    <h2 class="text-center m-3 ">Personel List</h2>


    <div class="row">

        <div class="col-md-9 mx-auto ">


        <table class="table table-borderless table-hover ">

            <thead>
                <tr>
                    <th>id</th>
                    <th>name</th>
                    <th>address</th>
                    <th>gender</th>
                    <th>cv</th>
                    <th>go to profile</th>
                </tr>
            </thead>
            <tbody>



                @{


                    foreach (var item in Model)
                    {
                        <tr>

                            <td>@item.Id</td>
                            <td>@item.Name</td>
                            <td>@item.Address</td>
                            <td> @Enum.GetName(typeof(Gender),item.Gender) </td>
                            <td>@item.Cv</td>
                            <td>
                                <a class="btn btn-outline-primary" asp-action="Profile" asp-controller="Personel" asp-route-id="@item.Id">
                                    @(item.Name + " 'ın profili")
                                </a>
                            </td>
                        </tr>
                    }


                }

            </tbody>

        </table>


        </div>
    </div>

WebApplication1/Views/Personel/Profile.cshtml
@{
    ViewData["Title"] = "Profile";
}

@model Personel

<h1 class="text-center">Profile</h1>


<a class="btn btn-success" asp-action="List" asp-controller="Personel" >   Geri Dön</a>
<ul class="list-group m-4">
    <li class="list-group-item">@Model.Id</li>
    <li class="list-group-item">@Model.Name</li>
    <li class="list-group-item">@Model.Address</li>
    <li class="list-group-item">@Model.Cv</li>
    <li class="list-group-item">
        
   
        @(Enum.GetName(typeof(Gender),Model.Gender))
        
    
    </li>
</ul>

WebApplication1/Views/Product/List.cshtml
@{
    ViewData["Title"] = "List";
}


@model List<Product>

<h1>List</h1>


<a asp-controller="product" asp-action="Register">geri dön</a>

@{

    foreach (var item in Model)
    {
        <p>
        
        
        @item.Id   @item.Name
        <a class="btn btn-outline-danger" asp-action="delete" asp-controller="product" asp-route-id="@item.Id">
        sil
        </a> 
        </p>
    }

}

WebApplication1/Views/Product/Register.cshtml
@{
    ViewData["Title"] = "Register";
}

@model Product
<h1>Register</h1>




<form asp-action="register" asp-controller="product" method="post"> 


    <input class="form-control" asp-for="Name" placeholder="name"/>
    <input class="form-control" asp-for="Id" placeholder="ıd"/>

    <button type="submit" class="btn btn-primary">add</button>
</form>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />


        @RenderSection("internalCss",false)
  
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_Layout2.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<html>
    <head>

    </head>
        <body style="background-color:red">




            @RenderBody()


        </body>


</html>

WebApplication1/Views/User/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h1>giriş başarıl</h1>

WebApplication1/Views/User/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>


@model Userİnformation

<form asp-action="login" asp-controller="user" method="post"> 



    <input class="form-control" asp-for="UserName" placeholder="user name" />
    <input class="form-control" asp-for="Password" type="password" />


    <button type="submit" class="btn btn-primary">login</button>

</form>